title: Fundamentos de Nodejs creando un API REST
description: >-
  En este curso aprenderemos los fundamentos de Nodejs y crearemos nuestro
  primer API Rest utilizando solo Nodejs que luego podrá ser consumido desde
  cualquier navegador.
template:
  repo: fundamentos-de-nodejs-creando-un-api-rest-template
  name: fundamentos-de-nodejs-creando-un-api-rest
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
